# Generated by Django 4.2.16 on 2024-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkiWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='autor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='rok',
            field=models.PositiveSmallIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='tytul',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
