# Generated by Django 4.2.16 on 2024-11-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkiWeb', '0002_ksiazka_autor_ksiazka_rok_alter_ksiazka_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='obrazy'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='ocena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='premiera',
            field=models.DateField(blank=True, null=True),
        ),
    ]
