# Generated by Django 4.2.16 on 2024-12-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkiWeb', '0003_ksiazka_obraz_ksiazka_ocena_ksiazka_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='opis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
